spring.application.name=devboard

spring.datasource.url=jdbc:postgresql://localhost:5432/devboard
spring.datasource.username=devboard_user
spring.datasource.password=devboard_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=NjQ3Y2Y2NzA4NjQ2YzE2YjQ3OTQ5NDY5NjEzM2Q2YzQ3OTViMjQwYjY4NzQ2YzNhNmY0MjFiZTY1NTQxMjM0NTY3ODkwYWJjZGVm
jwt.expiration=86400000